/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Customer;
import model.DeliveryPackage;
import model.Product;

/**
 *
 * @author tianzhichen
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    
    private DeliveryPackage delPackage;
    
    private Boolean validate = false;
    
    public CreateJPanel() {
        initComponents();
    }
    
    CreateJPanel(DeliveryPackage deliveeryPackage) {
        initComponents();
        
        // logic to take information from the user and store it in the delivery package
        this.delPackage = deliveeryPackage;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSave = new javax.swing.JButton();
        btnSaveProduct = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        packageWeight = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        productPrice1 = new javax.swing.JTextField();
        productId1 = new javax.swing.JTextField();
        productName1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        customerId1 = new javax.swing.JTextField();
        customerName1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(549, 206, -1, -1));

        btnSaveProduct.setText("SAVE PRODUCT");
        btnSaveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveProductActionPerformed(evt);
            }
        });
        add(btnSaveProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 388, 197, -1));

        jLabel8.setText("Package ID");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 85, -1, -1));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 82, 175, -1));

        jLabel9.setText("Weight");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 134, -1, -1));
        add(packageWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 131, 175, -1));

        jLabel10.setText("Product ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 272, -1, -1));

        jLabel11.setText("Product Name");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 328, -1, -1));

        jLabel12.setText("Product Price");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 388, -1, -1));
        add(productPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 388, 175, -1));
        add(productId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 269, 175, -1));
        add(productName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 325, 175, -1));

        jLabel13.setText("Customer Name");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 85, -1, -1));

        jLabel14.setText("Customer ID");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 134, -1, -1));
        add(customerId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 131, 175, -1));

        customerName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                customerName1FocusLost(evt);
            }
        });
        add(customerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 82, 175, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        // get the data
        String id = packageId.getText();
        String weight = packageWeight.getText();
        
        String customerId = customerId1.getText();
        String customerName = customerName1.getText();
        
        // store the data
        this.delPackage.setPackageId(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Double.valueOf(weight));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerId(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
        if(validate) {
            JOptionPane.showMessageDialog(null, "Please fill all fields.");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSaveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveProductActionPerformed
        // TODO add your handling code here:
        String productId = productId1.getText();
        String productName = productName1.getText();
        String productPrice = productPrice1.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId), productName, Double.valueOf(productPrice));
        
        JOptionPane.showMessageDialog(null, "Added Product!");
    }//GEN-LAST:event_btnSaveProductActionPerformed

    private void customerName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_customerName1FocusLost
        // TODO add your handling code here:
        System.out.println(customerName1.getText() + " -- the customer name");
        String name = customerName1.getText();
        
        if(name.isEmpty()) {
            // JOptionPane.showMessageDialog(null, "Please fill name.");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_customerName1FocusLost

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveProduct;
    private javax.swing.JTextField customerId1;
    private javax.swing.JTextField customerName1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWeight;
    private javax.swing.JTextField productId1;
    private javax.swing.JTextField productName1;
    private javax.swing.JTextField productPrice1;
    // End of variables declaration//GEN-END:variables
}
